### ISSUE TITLE
[feature request] preview size adjustment

### ISSUE THREAD

**Issue by OcAMD** [mezz/ItemZoom#1]
I first off want to say I love this mod! Thank you!

I would also like to request an enhancement if possible to allow 2 sizes to choose from. On my screen the current size is massive which works great to be able to see the true appearance that resource pack artists intended their artwork to be but just a tad to big to represent what it'll look like in world. The toggle is great with on and off so maybe it could be on, full size, and half sized. Thank you for your consideration.

Thank you for all the work on various mods such as JEI; as well as; the help you give to others like MatrexsVigil with Pam's HarvestCraft.

**Comment by mezz** [comment]
Thanks! That's a good suggestion.

**Comment by mezz** [comment]
The new version will let you set the zoom amount in the config. 
You can also set hotkeys to change the amount if you want to change it in-game.
Should be up on Curse in a little while.

**Comment by OcAMD** [comment]
Thank you, I love it! You didn't waste any time wow!
