### ISSUE TITLE
[Suggestion] Toggle for damage bar display

### ISSUE THREAD

**Issue by TehNut** [mezz/ItemZoom#11]
I'd rather just see the item without a giant durability bar on it.

**Comment by mezz** [comment]
Implemented here: https://github.com/mezz/ItemZoom/commit/a0502f6df7f7459e86dad2289043fdab987afb02
In version 1.7

**Comment by TehNut** [comment]
Would that solution for damage bars work for items with a custom rendering for the damage bar?

**Comment by mezz** [comment]
It wont work for all of them, but I'm a bit reluctant to copy all the vanilla rendering code required to do it 100%.

**Comment by TehNut** [comment]
Isn't there a method for rendering items without the overlays? (damage bar and stack size)

**Comment by mezz** [comment]
Yes but I made damage bar and stack size into two different config options. Maybe that wasn't the right solution.

**Comment by ProfessorProspector** [comment]
tbh I don't see any reason you'd ever want the stack size there at all

**Comment by mezz** [comment]
ItemZoom could be useful for people with low vision, so I thought the stack size might be useful.

**Comment by ProfessorProspector** [comment]
you can always recreate the stacksize effect or something

**Comment by mezz** [comment]
I think I'll just copy the vanilla code so it's done right.
I'll probably break Optifine or whatever but I think I'm done worrying about that.

**Comment by mezz** [comment]
Fixed in ItemZoom 1.8
