### ISSUE TITLE
NullPointerException when zooming

### ISSUE THREAD

**Issue by BinaryCrafter** [mezz/ItemZoom#2]
I bound the keypress shift + and shift - to the zoom feature, and after zooming out a few levels, whilst hovering over an arrow in my inventory, the game threw a NullPointerException.

Full stacktrace/details [here](http://pastebin.com/ELYf3eJZ)

**Comment by mezz** [comment]
Thanks for the report!
I think this is an old bug in JEI, try updating it and see if it fixes the issue.
