### ISSUE TITLE
[Enhancement] Add compat for 1.16.4  

### ISSUE THREAD

**Issue by jengendler** [mezz/ItemZoom#24]
If you're still actively working on this mod, I would like to submit an enhancement request to add compatibility support for 1.16.4.

I love this mod and am sorely missing it! It's definitely on my must-have mods list. Thank you for making it! :)

**Comment by GabuSilver** [comment]
Same here; I do Blogs in Amino Crafters, always using this really cool and original mod

**Comment by simplebunsen** [comment]
And if it already works for that version (which I'd assume), then simply tagging it 1.16.4 on curse would be enough to fix it without uploading anything.

**Comment by simplebunsen** [comment]
Till this is fixed, I've made an updated version that fixes this and works for 1.16.4. It's available here: https://www.curseforge.com/minecraft/mc-mods/itemzoom-rekindled

**Comment by mezz** [comment]
Thanks for the report! 
The code was ready for 1.16.4 some months ago but I needed an update from Forge for tooltips. 
I just checked and that change was completed a while ago now, so I have released the mod for 1.16.4 here: 
https://www.curseforge.com/minecraft/mc-mods/itemzoom/files/3174664
