### ISSUE TITLE
Item zoom COVERS recipe book for 1.16.5

### ISSUE THREAD

**Issue by JetpackRescue** [mezz/ItemZoom#31]
![2021-12-23_10 05 23](https://user-images.githubusercontent.com/49115565/147277430-e9aa543a-b818-41ff-9006-43213b91494e.png)

![2021-12-23_10 09 56](https://user-images.githubusercontent.com/49115565/147277656-1de333f7-7a77-46c5-9ae8-889fad9b8b3b.png)

Shown at gui level 2 and level 3 with optifine

You should have item zoom hide itself when the recipe book is open, or reposition itself further left at a smaller zoom level

**Comment by mezz** [comment]
Thanks for the report!
I have uploaded a version with fixes for this here: https://www.curseforge.com/minecraft/mc-mods/itemzoom/files/3603919
