### ISSUE TITLE
Update for 1.20 ?

### ISSUE THREAD

**Issue by Bootscreen** [mezz/ItemZoom#39]
hey, any plans on updating it for 1.20? i really want to try this mod :D

**Comment by Skyknightb** [comment]
As a builder, I miss having this mod around in 1.20, it's a must.

**Comment by Dragonsissiy** [comment]
Would also love to see a 1.20.x version. Helps visually challenged people such as myself better see the blocks before I place em.

**Comment by mezz** [comment]
Updated here: https://github.com/mezz/ItemZoom/pull/40
I'll release an update for 1.20.4 soon as well

**Comment by mezz** [comment]
a new 1.20.4 version is up on curseforge now
