### ISSUE TITLE
[Suggestion] Itemstack Type Zooming

### ISSUE THREAD

**Issue by InsomniaKitten** [mezz/ItemZoom#5]
A config to limit zooming to certain types of itemstacks, i.e only zoom block items and ignore 'item' items; and vice versa.

**Comment by mezz** [comment]
Unfortunately this is not a simple feature and I wont be able to add it.
Things like flowers, torches, rails, flower pots, glass panes, etc which display as flat are still considered Block items in code, while other 3d things like heads are not.
