### ISSUE TITLE
Formatting Error w/ Config GUI Title

### ISSUE THREAD

**Issue by SnowShock35** [mezz/ItemZoom#8]
Hi mezz,

I believe to have found an issue with ItemZoom, here are the details;

### Important Information

- Minecraft 1.11.2
- Minecraft Forge 13.20.0.2228
- ItemZoom 1.4

### Issue Description

Tl;Dr: See image, Formatting error with in-game config GUI title therefore causing it to display: `Formatting error ItemZoom Config`

### Issue Media

![Issue Screenshot (Incorrect Config GUI Title being displayed)](https://ss.blamesnow.co.uk/2017/04/1492461626-acca68bf.png)

### Issue Fix

So, if you were to go about fixing this the quick way, you could just do it the way it's done in JEI using the now deprecated class `net.minecraft.util.text.translation.I18n` and if you were to do that here's the code for it... However, I imagine you'll look for a better solution for this.

```java
private static String getTitle() {
	String key = "config.itemzoom.title";
	if (I18n.canTranslate(key)) {
		return I18n.translateToLocal(key).replace("%MODNAME", MOD_NAME);
	} else {
		return I18n.translateToFallback(key).replace("%MODNAME", MOD_NAME);
	}
}
```

**Comment by mezz** [comment]
Thanks!
Fixed in version 1.5
