### ISSUE TITLE
ItemZoom ignores Ender Compass config option

### ISSUE THREAD

**Issue by MrIbby** [mezz/ItemZoom#9]
The user can edit a config option for the Ender Compass mod so that the compass item must be in their inventory in order for it to work, but ItemZoom seems ignore this.

Here's the original post describing this: https://www.reddit.com/r/feedthebeast/comments/5wi9b5/small_but_useful_new_mod_from_mezz_itemzoom/deewjgb/

**Comment by mezz** [comment]
Thanks for the report!
I'm not doing anything too exotic with rendering, it should be very similar to vanilla. 
Can you put a breakpoint in your method to see what is happening?

**Comment by MrIbby** [comment]
Oops, I should have done this a long time ago... I currently don't have access to my main computer, but if I can set up the workspace on another one, I'll get back to you.

**Comment by mezz** [comment]
This has been fixed on their side.
